### ISSUE TITLE
Detech and recover from phabricator session errors

### ISSUE THREAD

**Issue by bd808** [bd808/tools-stashbot#10]
Errors look like this:
```
2016-05-01T22:18:21Z Stashbot     ERROR   : Failed to lookup info for T134098
Traceback (most recent call last):
  File "/data/project/stashbot/stashbot/bot.py", line 279, in do_phabecho
    info = self.phab.taskInfo(task)
  File "/data/project/stashbot/stashbot/phab.py", line 74, in taskInfo
    r = self.post('phid.lookup', {'names': [task]})
  File "/data/project/stashbot/stashbot/phab.py", line 70, in post
    raise Exception(resp['error_info'])
Exception: Session key is invalid.
```
Right now the only way to recover from the session invalidation is to restart the bot. It should be possible to detect this state automatically and create a new phab session. If that's too hard then it might be time to add some admin commands that can be sent to the bot to force a session restart.

**Comment by bd808** [comment]
Even better! Phab now supports using an api token directly in a session-less manner. See https://github.com/disqus/python-phabricator/pull/23/files for the really simple changes needed.
